Fix bug where public property is treated as a getter
This caused me the following error in the front end

TypeError: whitelistContract.numAddressesWhitelisted is not a function